version: '3.9'

services:
  app:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend/service:1.0.0
    container_name: backend_test
    restart: unless-stopped
    volumes:
      - ./:/usr/src/backend
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - backend

  database: 
    image: postgres:14.1-alpine
    container_name: backend_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/

networks:
  backend:
    driver: bridge
  
volumes:
  database-data: